# Form implementation generated from reading ui file '/Users/uyennhi/Downloads/FINAL_REPORT_PROGRAMMING-TECHNIQUES/Final_Report/ui/Statistics/StatisticsMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StatisticsWindow(object):
    def setupUi(self, StatisticsWindow):
        StatisticsWindow.setObjectName("StatisticsWindow")
        StatisticsWindow.resize(700, 400)
        StatisticsWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(parent=StatisticsWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(207, 227, 182);")
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 681, 31))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(27)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(31, 64, 31)")
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 661, 271))
        font = QtGui.QFont()
        font.setFamily("PT Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(600, 330, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(14)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("background-color: rgb(51, 89, 23);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -1, 711, 401))
        self.label.setStyleSheet("background-color: rgb(207, 227, 182);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_title.raise_()
        self.groupBox.raise_()
        self.pushButtonBack.raise_()
        StatisticsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StatisticsWindow)
        QtCore.QMetaObject.connectSlotsByName(StatisticsWindow)

    def retranslateUi(self, StatisticsWindow):
        _translate = QtCore.QCoreApplication.translate
        StatisticsWindow.setWindowTitle(_translate("StatisticsWindow", "Animal Rescue System - Statistics"))
        self.label_title.setText(_translate("StatisticsWindow", "Statistics"))
        self.groupBox.setTitle(_translate("StatisticsWindow", "Chart Visualization:"))
        self.pushButtonBack.setText(_translate("StatisticsWindow", "Back"))
