# Form implementation generated from reading ui file 'D:\LaNguyenMyDung_K254111447_K25411E\Python\FINAL_REPORT_PROGRAMMING-TECHNIQUES\Dung_BIAWEB\uiBIAWEB\BIAWEB.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\LaNguyenMyDung_K254111447_K25411E\\Python\\FINAL_REPORT_PROGRAMMING-TECHNIQUES\\Dung_BIAWEB\\uiBIAWEB\\../image/Bia.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButtonSignIn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSignIn.setGeometry(QtCore.QRect(440, 240, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButtonSignIn.setFont(font)
        self.pushButtonSignIn.setStyleSheet("background-color: rgb(94, 167, 15);\n"
"font: 81 20pt \"Rockwell Extra Bold\";\n"
"\n"
"\n"
"color: rgb(255, 248, 23);")
        self.pushButtonSignIn.setObjectName("pushButtonSignIn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonSignIn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#005500;\">Sign Up</span></p></body></html>"))
        self.pushButtonSignIn.setText(_translate("MainWindow", "Sign In"))
