# Form implementation generated from reading ui file '/Users/uyennhi/Documents/HK2_25_26/Ky_thuat_lap_trinh/FINAL_REPORT/FINAL_REPORT_PROGRAMMING-TECHNIQUES/employee_management/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 341))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/uyennhi/Documents/HK2_25_26/Ky_thuat_lap_trinh/FINAL_REPORT/FINAL_REPORT_PROGRAMMING-TECHNIQUES/employee_management/Quản lý nhân viên (1).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEditEnter = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditEnter.setGeometry(QtCore.QRect(500, 30, 161, 21))
        self.lineEditEnter.setObjectName("lineEditEnter")
        self.lineEditFullName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditFullName.setGeometry(QtCore.QRect(430, 100, 241, 20))
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.lineEditRole = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditRole.setGeometry(QtCore.QRect(430, 130, 241, 20))
        self.lineEditRole.setObjectName("lineEditRole")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPhone.setGeometry(QtCore.QRect(430, 160, 241, 20))
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(430, 220, 241, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(430, 190, 241, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEditShift = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditShift.setGeometry(QtCore.QRect(430, 220, 241, 20))
        self.lineEditShift.setObjectName("lineEditShift")
        self.lineEditAssignedPets = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditAssignedPets.setGeometry(QtCore.QRect(430, 190, 241, 20))
        self.lineEditAssignedPets.setObjectName("lineEditAssignedPets")
        self.lineEditStatus = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditStatus.setGeometry(QtCore.QRect(430, 250, 241, 20))
        self.lineEditStatus.setObjectName("lineEditStatus")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(60, 100, 241, 211))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 239, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutEmployee = QtWidgets.QVBoxLayout()
        self.verticalLayoutEmployee.setObjectName("verticalLayoutEmployee")
        self.verticalLayout_2.addLayout(self.verticalLayoutEmployee)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAdd.setGeometry(QtCore.QRect(510, 290, 161, 31))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.pushButtonAdd.setFont(font)
        self.pushButtonAdd.setStyleSheet("background-color: rgb(123, 177, 95);\n"
"font: 13pt \".AppleSystemUIFont\";")
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Employees Management"))
        self.lineEditEnter.setPlaceholderText(_translate("MainWindow", "Enter information"))
        self.pushButtonAdd.setText(_translate("MainWindow", "Add new employee"))
