# Form implementation generated from reading ui file '/Users/uyennhi/Downloads/FINAL_REPORT_PROGRAMMING-TECHNIQUES/Final_Report/ui/ForgetPassword/ForgetPassWordMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/uyennhi/Downloads/FINAL_REPORT_PROGRAMMING-TECHNIQUES/Final_Report/ui/ForgetPassword/../../images/ForgetPassword.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(320, 100, 341, 201))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEditTracedPassword = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditTracedPassword.setGeometry(QtCore.QRect(20, 120, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        self.lineEditTracedPassword.setFont(font)
        self.lineEditTracedPassword.setStyleSheet("background-color: rgb(44, 85, 0);\n"
"color: rgb(208, 208, 208);\n"
"")
        self.lineEditTracedPassword.setText("")
        self.lineEditTracedPassword.setObjectName("lineEditTracedPassword")
        self.pushButtonTracePassword = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonTracePassword.setGeometry(QtCore.QRect(80, 70, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonTracePassword.setFont(font)
        self.pushButtonTracePassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonTracePassword.setStyleSheet("background-color: rgb(44, 85, 0);\n"
"color: rgb(255, 239, 114);")
        self.pushButtonTracePassword.setObjectName("pushButtonTracePassword")
        self.pushButtonContinueSignIn = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonContinueSignIn.setGeometry(QtCore.QRect(110, 170, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Lao MN")
        font.setUnderline(True)
        self.pushButtonContinueSignIn.setFont(font)
        self.pushButtonContinueSignIn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonContinueSignIn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;                \n"
"    color: #1e3d08;                \n"
"    text-decoration: underline;   \n"
"}\n"
"QPushButton:hover {\n"
"    color: red;                \n"
"}")
        self.pushButtonContinueSignIn.setObjectName("pushButtonContinueSignIn")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPhone.setGeometry(QtCore.QRect(20, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        self.lineEditPhone.setFont(font)
        self.lineEditPhone.setStyleSheet("background-color: rgb(44, 85, 0);\n"
"color: rgb(208, 208, 208);\n"
"")
        self.lineEditPhone.setText("")
        self.lineEditPhone.setObjectName("lineEditPhone")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditTracedPassword.setPlaceholderText(_translate("MainWindow", "Your Password"))
        self.pushButtonTracePassword.setText(_translate("MainWindow", "Trace Password"))
        self.pushButtonContinueSignIn.setText(_translate("MainWindow", "Continue Sign In"))
        self.lineEditPhone.setPlaceholderText(_translate("MainWindow", "Your Phone number"))
