# Form implementation generated from reading ui file 'D:\LaNguyenMyDung_K254111447_K25411E\Python\FINAL_REPORT_PROGRAMMING-TECHNIQUES\Dung_BIAWEB\uiSignIn\Signin.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\LaNguyenMyDung_K254111447_K25411E\\Python\\FINAL_REPORT_PROGRAMMING-TECHNIQUES\\Dung_BIAWEB\\uiSignIn\\../image/SignIn.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(320, 100, 341, 201))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditEmail.setGeometry(QtCore.QRect(20, 10, 301, 41))
        self.lineEditEmail.setStyleSheet("background-color: rgb(44, 85, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(208, 208, 208);\n"
"")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPassword.setGeometry(QtCore.QRect(20, 60, 301, 41))
        self.lineEditPassword.setStyleSheet("background-color: rgb(44, 85, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(208, 208, 208);")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonSignIn = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSignIn.setGeometry(QtCore.QRect(90, 120, 171, 41))
        self.pushButtonSignIn.setStyleSheet("background-color: rgb(44, 85, 0);\n"
"font: 81 20pt \"Rockwell Extra Bold\";\n"
"color: rgb(255, 239, 114);")
        self.pushButtonSignIn.setObjectName("pushButtonSignIn")
        self.pushButtonForgetPass = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonForgetPass.setGeometry(QtCore.QRect(120, 170, 121, 20))
        self.pushButtonForgetPass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonForgetPass.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;                \n"
"    color: #1e3d08;                \n"
"    text-decoration: underline;   \n"
"}\n"
"QPushButton:hover {\n"
"    color: red;                \n"
"}")
        self.pushButtonForgetPass.setObjectName("pushButtonForgetPass")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditEmail.setText(_translate("MainWindow", "   Email adress or phone number"))
        self.lineEditPassword.setText(_translate("MainWindow", "   Password"))
        self.pushButtonSignIn.setText(_translate("MainWindow", "Sign In"))
        self.pushButtonForgetPass.setText(_translate("MainWindow", "Forget Password?"))
