# Form implementation generated from reading ui file 'D:\LaNguyenMyDung_K254111447_K25411E\Python\FINAL_REPORT_PROGRAMMING-TECHNIQUES\Final_Report\ui\UserSystemMainWindow\UserSystemMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 700, 400))
        self.label.setMinimumSize(QtCore.QSize(700, 400))
        self.label.setMaximumSize(QtCore.QSize(700, 400))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\LaNguyenMyDung_K254111447_K25411E\\Python\\FINAL_REPORT_PROGRAMMING-TECHNIQUES\\Final_Report\\ui\\UserSystemMainWindow\\../../image/UserSystem.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.BtnSignUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BtnSignUp.setGeometry(QtCore.QRect(390, 10, 301, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.BtnSignUp.setFont(font)
        self.BtnSignUp.setStyleSheet("background-color: rgb(44, 83, 8);\n"
"color: rgb(238, 228, 90);")
        self.BtnSignUp.setObjectName("BtnSignUp")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-6, -1, 711, 401))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\LaNguyenMyDung_K254111447_K25411E\\Python\\FINAL_REPORT_PROGRAMMING-TECHNIQUES\\Final_Report\\ui\\UserSystemMainWindow\\../image/interface.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label.raise_()
        self.BtnSignUp.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BtnSignUp.setText(_translate("MainWindow", "Sign up to adopt a lovely pet RIGHT NOW !!"))
