# Form implementation generated from reading ui file 'D:\de Uni _UEL\HK2\Kỹ thuật lập trình\FINAL_REPORT_PROGRAMMING-TECHNIQUES\ui\ForgetPassword\ForgertPassWordMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 400)
        MainWindow.setMinimumSize(QtCore.QSize(700, 400))
        MainWindow.setMaximumSize(QtCore.QSize(700, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\de Uni _UEL\\HK2\\Kỹ thuật lập trình\\FINAL_REPORT_PROGRAMMING-TECHNIQUES\\ui\\ForgetPassword\\../image/Forget_Password.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(320, 100, 341, 201))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPhone.setGeometry(QtCore.QRect(20, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        self.lineEditPhone.setFont(font)
        self.lineEditPhone.setStyleSheet("background-color: rgb(44, 85, 0);\n"
"color: rgb(208, 208, 208);\n"
"")
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.lineEditTracedPassword = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditTracedPassword.setGeometry(QtCore.QRect(20, 110, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(14)
        self.lineEditTracedPassword.setFont(font)
        self.lineEditTracedPassword.setStyleSheet("background-color: rgb(44, 85, 0);\n"
"color: rgb(208, 208, 208);\n"
"")
        self.lineEditTracedPassword.setObjectName("lineEditTracedPassword")
        self.pushButtonTracePassword = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonTracePassword.setGeometry(QtCore.QRect(100, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonTracePassword.setFont(font)
        self.pushButtonTracePassword.setStyleSheet("background-color: rgb(44, 85, 0);\n"
"color: rgb(255, 239, 114);")
        self.pushButtonTracePassword.setObjectName("pushButtonTracePassword")
        self.pushButtonContinueSignIn = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonContinueSignIn.setGeometry(QtCore.QRect(110, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(13)
        font.setUnderline(True)
        self.pushButtonContinueSignIn.setFont(font)
        self.pushButtonContinueSignIn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonContinueSignIn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;                \n"
"    color: #1e3d08;                \n"
"    text-decoration: underline;   \n"
"}\n"
"QPushButton:hover {\n"
"    color: red;                \n"
"}")
        self.pushButtonContinueSignIn.setObjectName("pushButtonContinueSignIn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditPhone.setText(_translate("MainWindow", "  Enter phone number"))
        self.lineEditTracedPassword.setText(_translate("MainWindow", "   Your Password"))
        self.pushButtonTracePassword.setText(_translate("MainWindow", "Trace Password"))
        self.pushButtonContinueSignIn.setText(_translate("MainWindow", "Continue Sign In"))
